name=SerialRGBLed
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=For WS2811 and WS2812 LEDs and LED Drivers
paragraph=**PRELIMINARY**
category=Display
url=https://github.com/mumanchu/SerialRGBLed
architectures=STM32
