name=SerialRGBLed
version=1.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=WS2812 and WS2811 RGB LED Driver
paragraph=With Remote Control Transmitter (RMT) version for ESP32
category=Display
includes=SerialRGBLed.h
url=https://github.com/mumanchu/SerialRGBLed
architectures=esp32,stm32
